# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='slug')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is enabled')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is enabled')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is enabled')),
                ('ledger_type', models.CharField(choices=[('cashout', 'Cash Out'), ('principal', 'Principal')], max_length=200)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Journal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is enabled')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase')], max_length=200)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
