# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='ledger_type',
            new_name='name',
        ),
    ]
