# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170907_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='accounts.Account'),
        ),
    ]
