# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170907_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ledger',
        ),
        migrations.AddField(
            model_name='transaction',
            name='journal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.Journal'),
            preserve_default=False,
        ),
    ]
